[package]
name = "chat-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epistle = { path = "../epistle" }
crossterm = "0.22.1"
tui = "0.17.0"
rmp-serde = "1.0.0"
tui-input = "0.1.2"
