[package]
name = "tcp-cilent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epistle = { path = "../epistle" }
rmp-serde = "1.0.0"
